### ISSUE TITLE
[run error] process_adc_bin2np.py

### ISSUE THREAD

**Issue by CHB-learner** [yujheli/Pitt-Radar#6]
When I run 
python process_adc_bin2np.py --raw_data radar_bin/ --output radar_numpy/

it occurs:
(393216,)    # print(adc_data.shape)
Traceback (most recent call last):
  File "process_adc_bin2np.py", line 78, in <module>
    adc_data2frame = dca.organize(
  File "/home/ubuntu/miniconda3/envs/pitt_SR/lib/python3.8/site-packages/mmwave/dataloader/adc.py", line 280, in organize
    return ret.reshape((num_chirps, num_rx, num_samples))
ValueError: cannot reshape array of size 196608 into shape (384,4,256)

dataset is your open source

"[March 2023] We release the first version of 5k frames of our dataset at the [link](https://drive.google.com/drive/folders/1v2w7F-DQBNCthbl0z_h-EbTZfK8A0IgB?usp=share_link) in the resolution of 128 samples in range. Other parts of the dataset will be released later. Stay tuned."

I don't know where the problem lies。
Looking forward to your early reply!

**Comment by CHB-learner** [comment]
Do these parameters need to be modified？

# 
numADCSamples = 128
numTxAntennas = 3
numRxAntennas = 4
numLoopsPerFrame = 128
numChirpsPerFrame = numTxAntennas * numLoopsPerFrame
num_angle_bins = 128

numADCSamples = 256
num_angle_bins = 256

**Comment by yujheli** [comment]
Sorry for the late reply. 

You will need to change
numADCSamples = 128
num_angle_bins = 128
or comment last two lines
