### ISSUE TITLE
Questions about the super-resolution performance

### ISSUE THREAD

**Issue by RoboticsZhang** [yujheli/Pitt-Radar#8]
Hello, thank you for your novel and solid work, as well as the code and data open-sourcing.
According to the paper and the code, it seems that the ADC-SR takes adc data from 4 receivers as the input, and that from 12 receivers as the output. I wonder that if ADC-SR can take  adc data from 12 receivers as the input, and output adc data from more hallucinated  receivers? That is, given a single-chip radar with 3TX and 4RX, could we use ADC-SR to generate super -resolution adc data with more hallucinated  receivers? Thank you!

**Comment by yujheli** [comment]
We have tried and that also works for generating super-super resolution. However, since we do not have the real high number of receivers, there is no way to verify the higher settings.

**Comment by RoboticsZhang** [comment]
> We have tried and that also works for generating super-super resolution. However, since we do not have the real high number of receivers, there is no way to verify the higher settings.

Thank you for your reply. I will close this issue then.

**Comment by yujheli** [comment]
I found the visualization of super-super resolution I had last year below (4 receivers vs 12 receivers vs 108 receivers):
<img width="732" alt="image" src="https://github.com/yujheli/Pitt-Radar/assets/23270045/223e75f6-015b-431b-b292-9bc995200851">

**Comment by RoboticsZhang** [comment]
Thank you!
